CREATE DATABASE `valr_bot_db` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;


-- valr_bot_db.ACCOUNT_BALANCES definition

CREATE TABLE `ACCOUNT_BALANCES` (
  `CURRENCY` text,
  `AVAILABLE_AMOUNT` double DEFAULT NULL,
  `RESERVED_AMOUNT` double DEFAULT NULL,
  `LEND_RESERVED` double DEFAULT NULL,
  `BORROW_RESERVED` double DEFAULT NULL,
  `BORROWED_AMOUNT` double DEFAULT NULL,
  `TOTAL_BALANCE` double DEFAULT NULL,
  `TIMESTAMP` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



-- valr_bot_db.API_CONNECTION_PARAMS definition

CREATE TABLE `API_CONNECTION_PARAMS` (
  `VARIABLE_NAME` varchar(200) DEFAULT NULL,
  `VARIABLE_VALUE` varchar(200) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- valr_bot_db.MARKET_SUMMARY definition

CREATE TABLE `MARKET_SUMMARY` (
  `CURRENCY_PAIR` text,
  `LAST_TRADE_PRICE` double DEFAULT NULL,
  `PREVIOUS_CLOSE_PRICE` double DEFAULT NULL,
  `HIGH_PRICE` double DEFAULT NULL,
  `LOW_PRICE` double DEFAULT NULL,
  `CHANGE_FROM_PREVIOUS` double DEFAULT NULL,
  `TIMESTAMP` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



-- valr_bot_db.MARKET_SUMMARY definition

CREATE TABLE `MARKET_SUMMARY` (
  `CURRENCY_PAIR` text,
  `LAST_TRADE_PRICE` double DEFAULT NULL,
  `PREVIOUS_CLOSE_PRICE` double DEFAULT NULL,
  `HIGH_PRICE` double DEFAULT NULL,
  `LOW_PRICE` double DEFAULT NULL,
  `CHANGE_FROM_PREVIOUS` double DEFAULT NULL,
  `TIMESTAMP` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- valr_bot_db.TRADE_PAIR_WHITELIST definition

CREATE TABLE `TRADE_PAIR_WHITELIST` (
  `SYMBOL` varchar(10) DEFAULT NULL,
  `ACTIVE` tinyint(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- valr_bot_db.TRADING_PAIRS definition


CREATE TABLE `TRADING_PAIRS` (
  `SYMBOL` text,
  `BASE_CURRENCY` text,
  `QUOTE_CURRENCY` text,
  `ACTIVE` tinyint(1) DEFAULT NULL,
  `MIN_BASE_AMOUNT` double DEFAULT NULL,
  `MAX_BASE_AMOUNT` double DEFAULT NULL,
  `MIN_QUOTE_AMOUNT` double DEFAULT NULL,
  `MAX_QUOTE_AMOUNT` double DEFAULT NULL,
  `MARGIN_TRADING_ALLOWED` tinyint(1) DEFAULT NULL,
  `TIMESTAMP` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- valr_bot_db.DAILY_RECON definition

CREATE TABLE `DAILY_RECON` (
  `DATE` date NOT NULL,
  `CURRENCY` varchar(10) DEFAULT NULL,
  `AVAILABLE_AMOUNT` float DEFAULT NULL,
  `TOTAL_BALANCE` double DEFAULT NULL,
  `LAST_TRADE_PRICE` float DEFAULT NULL,
  `AVAILABLE_AMOUNT_ZAR` float DEFAULT NULL,
  `RESERVED_AMOUNT_ZAR` double DEFAULT NULL,
  `TOTAL_BALANCE_ZAR` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



-- valr_bot_db.DEPOSITS_WITHDRAWALS definition

CREATE TABLE valr_bot_db.DEPOSITS_WITHDRAWALS (
	TRANSACTION_TYPE varchar(50) NULL,
	`DATE` DATE NULL,
	CURRENCY varchar(10) NULL,
	CREDIT_AMOUNT FLOAT NULL,
	LAST_TRADE_PRICE DECIMAL NULL,
	TOTAL_VALUE_ZAR DOUBLE NULL,
	CREDIT_CURRENCY varchar(10) NULL
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

